name: fastapi-ci

on:
  push:
    paths:
      - "fastapi/**"
      - ".github/workflows/fastapi-ci.yml"

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                python-version: 3.11
            - name: Install pipenv
              run: pip install pipenv

            - name: run tests
              working-directory: ./fastapi
              run: |
                pipenv install --dev 
                pipenv run coverage run -m pytest -v .
                pipenv run coverage report -m
              
